# Generated by Django 4.2.1 on 2023-06-10 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='status',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='user',
        ),
    ]
