# Generated by Django 4.2.1 on 2023-06-12 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_remove_todo_priority_remove_todo_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='category',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='status',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='urgency',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
