# Generated by Django 4.2.1 on 2023-06-12 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_todo_category_todo_status_todo_urgency'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='assigned_user',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
