# Generated by Django 4.2.1 on 2023-06-12 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_todo_assigned_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='assigned_user',
            new_name='assignedTo',
        ),
    ]
