# Generated by Django 4.2.1 on 2023-06-13 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
