# Generated by Django 4.2.1 on 2023-06-16 20:34

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='assignedTo',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
