# Generated by Django 4.2.1 on 2023-06-28 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0010_database'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Database',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='color',
            field=models.CharField(default='', max_length=50),
        ),
    ]
