# Generated by Django 4.2.1 on 2023-06-28 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0011_delete_database_alter_userprofile_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='color',
            field=models.CharField(default='black', max_length=50),
        ),
    ]
